[project]
name = "mssqldump"
version = "0.1.0"
description = "Dump MSSQL database to SQL file"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pyodbc>=5.2.0",
]
